import type { Metadata } from "next";
import localFont from "next/font/local";
import { Cormorant_Garamond, Mrs_Saint_Delafield } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const cormorantGaramond = Cormorant_Garamond({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-cormorant-garamond',
});

const mrsSaintDelafield = Mrs_Saint_Delafield({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-mrs-saint-delafield',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} ${mrsSaintDelafield.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}